const JOB_TYPES = Object.freeze({
  CREATE_TOKEN: 'CREATE_TOKEN',
  TRANSFER_TOKEN: 'TRANSFER_TOKEN',
  UPDATE_TOKEN: 'UPDATE_TOKEN'
});

const JOB_STATUS = Object.freeze({
  // Stage 1 - accept job
  ACCEPTED: 'ACCEPTED',

  // Stage 2 - push Metadata to IPFS (create or update action)
  METADATA_CREATED: 'METADATA_CREATED',

  // Stage 3 - submit txs to network
  TRANSACTION_SENT: 'TRANSACTION_SENT',

  // Stage 4 - check transaction complete/failed
  JOB_COMPLETE: 'JOB_COMPLETE',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
});

const NEXT_STATES = {
  [JOB_STATUS.ACCEPTED]: [JOB_STATUS.METADATA_CREATED],
  [JOB_STATUS.METADATA_CREATED]: [JOB_STATUS.TRANSACTION_SENT],
  [JOB_STATUS.TRANSACTION_SENT]: [JOB_STATUS.JOB_COMPLETE, JOB_STATUS.TRANSACTION_FAILED],
  [JOB_STATUS.JOB_COMPLETE]: [], // No valid transition
  [JOB_STATUS.TRANSACTION_FAILED]: [], // No valid transition
};

module.exports = {
  JOB_TYPES,
  JOB_STATUS,
  NEXT_STATES
};
