
const JOB_TYPES = Object.freeze({
  CREATE_TOKEN: 'CREATE_TOKEN',
  TRANSFER_TOKEN: 'TRANSFER_TOKEN',
  UPDATE_TOKEN: 'UPDATE_TOKEN'
});

// ACCEPTED -> CREATING_METADATA -> METADATA_CREATED -> SENDING_TRANSACTION -> TRANSACTION_SENT -> TRANSACTION_FAILED
//          -> FAILED                                -> TRANSACTION_FAILED

const JOB_STATUS = Object.freeze({
  CREATED: 'CREATED',
  // IPFS push
  PUSH_TO_IPFS: 'PUSH_TO_IPFS',
  FAILED_TO_PUSH_TO_IPFS: 'FAILED_TO_PUSH_TO_IPFS',
  // Txs push
  TRANSACTION_SUBMITTED: "TRANSACTION_SUBMITTED",
  TRANSACTION_FAILED: "TRANSACTION_FAILED",
});

module.exports = {
  JOB_TYPES,
  JOB_STATUS
};
